[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "archolt"
authors = [{name = "Arch Software", email = "devs@archsoftware.com.br"}]
dynamic = ["version", "description"]
